export const pathnames = {
	"/": {
		es: "/",
		en: "/",
		fr: "/",
		pt: "/",
	},
	"/excursions": {
		es: "/excursiones",
		en: "/excursions",
		pt: "/excursoes",
		fr: "/excursions",
	},
	"/excursions/[excursionSlug]": {
		es: "/excursiones/[excursionSlug]",
		en: "/excursions/[excursionSlug]",
		pt: "/excursoes/[excursionSlug]",
		fr: "/excursions/[excursionSlug]",
	},
	"/programs": {
		es: "/programas",
		en: "/programs",
		pt: "/programas",
		fr: "/programs",
	},
	"/programs/[programSlug]": {
		es: "/programas/[programSlug]",
		en: "/programs/[programSlug]",
		pt: "/programas/[programSlug]",
		fr: "/programs/[programSlug]",
	},
	"/cart": {
		es: "/carrito",
		en: "/cart",
		pt: "/carrinho",
		fr: "/panier",
	},
	"/cart/checkout": {
		es: "/carrito/comprar",
		en: "/cart/checkout",
		pt: "/carrinho/checkout",
		fr: "/panier/checkout",
	},
	"/cart/checkout/payment/[bookingId]": {
		es: "/carrito/comprar/pago/[bookingId]",
		en: "/cart/checkout/payment/[bookingId]",
		pt: "/carrinho/checkout/pagamento/[bookingId]",
		fr: "/panier/checkout/paiement/[bookingId]",
	},
	"/services": {
		es: "/servicios",
		en: "/services",
		pt: "/servicos",
		fr: "/services",
	},
	"/about-destiny/[destiny-id]": {
		es: "/acerca-del-destino/[destiny-id]",
		en: "/about-destiny/[destiny-id]",
		pt: "/sobre-o-destino/[destiny-id]",
		fr: "/a-propos-de-la-destination/[destiny-id]",
	},
	"/about-destiny/como-llegar": {
		es: "/acerca-del-destino/como-llegar",
		en: "/about-destiny/how-to-get-there",
		pt: "/sobre-o-destino/como-chegar",
		fr: "/a-propos-de-la-destination/comment-arriver",
	},
	"/about-destiny/festividades-y-eventos": {
		es: "/acerca-del-destino/festividades-y-eventos",
		en: "/about-destiny/festivities-and-events",
		pt: "/sobre-o-destino/festividades-e-eventos",
		fr: "/a-propos-de-la-destination/festivites-et-evenements",
	},
	"/about-us/faq": {
		es: "/acerca-de-nosotros/preguntas-frecuentes",
		en: "/about-us/faq",
		pt: "/sobre-nos/faq",
		fr: "/a-propos-de-nous/faq",
	},
	"/about-us/our-team": {
		es: "/acerca-de-nosotros/nuestro-equipo",
		en: "/about-us/our-team",
		pt: "/sobre-nos/nossa-equipe",
		fr: "/a-propos-de-nous/notre-equipe",
	},
	"/about-us/sustainability": {
		es: "/acerca-de-nosotros/sustentabilidad",
		en: "/about-us/sustainability",
		pt: "/sobre-nos/sustentabilidade",
		fr: "/a-propos-de-nous/soutenabilite",
	},
	"/about-us/our-history": {
		es: "/acerca-de-nosotros/nuestra-historia",
		en: "/about-us/our-history",
		pt: "/sobre-nos/nossa-historia",
		fr: "/a-propos-de-nous/notre-histoire",
	},
	"/about-us/sustentability": {
		es: "/acerca-de-nosotros/sustentabilidad",
		en: "/about-us/sustentability",
		pt: "/sobre-nos/sustentabilidade",
		fr: "/a-propos-de-nous/soutenabilite",
	},
	"/about-us/policies": {
		es: "/acerca-de-nosotros/politicas",
		en: "/about-us/policies",
		pt: "/sobre-nos/politicas",
		fr: "/a-propos-de-nous/politiques",
	},
	"/contact": {
		es: "/contacto",
		en: "/contact",
		pt: "/contato",
		fr: "/contact",
	},
	"/work-with-us": {
		es: "/trabaja-con-nosotros",
		en: "/work-with-us",
		pt: "/trabalhe-conosco",
		fr: "/travailler-avec-nous",
	},

	// Admin
	"/admin/dashboard": {
		es: "/admin/panel",
		en: "/admin/dashboard",
		pt: "/admin/dashboard",
		fr: "/admin/dashboard",
	},
	"/admin/dashboard/excursions": {
		es: "/admin/panel/excursiones",
		en: "/admin/dashboard/excursions",
		pt: "/admin/dashboard/excursoes",
		fr: "/admin/dashboard/excursions",
	},
	"/admin/dashboard/excursions/[excursionSlug]": {
		es: "/admin/panel/excursiones/[excursionSlug]",
		en: "/admin/dashboard/excursions/[excursionSlug]",
		pt: "/admin/dashboard/excursoes/[excursionSlug]",
		fr: "/admin/dashboard/excursions/[excursionSlug]",
	},
	"/admin/dashboard/excursions/create": {
		es: "/admin/panel/excursiones/crear",
		en: "/admin/dashboard/excursions/create",
		pt: "/admin/dashboard/excursoes/criar",
		fr: "/admin/dashboard/excursions/create",
	},
	"/admin/dashboard/programs": {
		es: "/admin/panel/programas",
		en: "/admin/dashboard/programs",
		pt: "/admin/dashboard/programas",
		fr: "/admin/dashboard/programs",
	},
	"/admin/dashboard/programs/[programSlug]": {
		es: "/admin/panel/programas/[programSlug]",
		en: "/admin/dashboard/programs/[programSlug]",
		pt: "/admin/dashboard/programas/[programSlug]",
		fr: "/admin/dashboard/programs/[programSlug]",
	},
	"/admin/dashboard/programs/create": {
		es: "/admin/panel/programas/crear",
		en: "/admin/dashboard/programs/create",
		pt: "/admin/dashboard/programas/criar",
		fr: "/admin/dashboard/programs/create",
	},
	"/admin/dashboard/zones": {
		es: "/admin/panel/zonas",
		en: "/admin/dashboard/zones",
		pt: "/admin/dashboard/zonas",
		fr: "/admin/dashboard/zones",
	},
	"/admin/dashboard/zones/[zoneSlug]": {
		es: "/admin/panel/zonas/[zoneSlug]",
		en: "/admin/dashboard/zones/[zoneSlug]",
		pt: "/admin/dashboard/zonas/[zoneSlug]",
		fr: "/admin/dashboard/zones/[zoneSlug]",
	},
	"/admin/dashboard/zones/create": {
		es: "/admin/panel/zonas/crear",
		en: "/admin/dashboard/zones/create",
		pt: "/admin/dashboard/zonas/criar",
		fr: "/admin/dashboard/zones/create",
	},
	"/admin/dashboard/orders": {
		es: "/admin/panel/ordenes",
		en: "/admin/dashboard/orders",
		pt: "/admin/dashboard/pedidos",
		fr: "/admin/dashboard/orders",
	},
	"/admin/dashboard/orders/[orderId]": {
		es: "/admin/panel/ordenes/[orderId]",
		en: "/admin/dashboard/orders/[orderId]",
		pt: "/admin/dashboard/pedidos/[orderId]",
		fr: "/admin/dashboard/orders/[orderId]",
	},
	"/admin/dashboard/subscribers": {
		es: "/admin/panel/suscriptores",
		en: "/admin/dashboard/subscribers",
		pt: "/admin/dashboard/assinantes",
		fr: "/admin/dashboard/subscribers",
	},
}
